on:
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        required: true
        default: '3.11'
  release:
    types:
      - published
      - edited

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install `uv` and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync

      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'build.spec'
          upload_exe_with_name: 'auto-heroic-categories'

    #   - name: Upload artifact
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: auto-heroic-categories
    #       path: ./dist/auto-heroic-categories

  upload-to-release:
    needs: pyinstaller-build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'   # ← skip on workflow_dispatch
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: auto-heroic-categories
          path: ./dist/

      - name: Upload Executable to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/auto-heroic-categories
          asset_name: auto-heroic-categories
          asset_content_type: application/octet-stream